# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - binary: kubectl-cred
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: gjbae1212
    name: kubectl-cred
brews:
  - name: kubectl-cred
    tap:
      owner: gjbae1212
      name: homebrew-kubectl-cred
    commit_author:
      name: gjbae1212
      email: gjbae1212@gmail.com
    description: "kubectl-cred is a kubernetes plugin to which switch to contexts using an interactive CLI."
