apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cred
spec:
  version: {{ .TagName }}
  homepage: https://github.com/gjbae1212/kubectl-cred
  shortDescription: kubectl-cred is a kubernetes plugin to which switch to contexts and namespaces and clusters using an interactive CLI.
  description: |
    kubectl-cred is a kubernetes plugin to which switch to contexts and namespaces and clusters using an interactive CLI.

    # Switch context using an interactive CLI.
    kubectl cred ctx

    # Switch namespace using an interactive CLI.
    kubectl cred ns

    # Show your all of contexts information formatted tree.
    kubectl cred ls

    # Show your current context information.
    kubectl cred current

    # Rename context name in k8s config, using an interactive CLI.
    kubectl cred rename
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/gjbae1212/kubectl-cred/releases/download/{{ .TagName }}/kubectl-cred_{{ .TagName }}_Darwin_x86_64.tar.gz" .TagName }}
    bin: kubectl-cred
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/gjbae1212/kubectl-cred/releases/download/{{ .TagName }}/kubectl-cred_{{ .TagName }}_Linux_x86_64.tar.gz" .TagName }}
    bin: kubectl-cred
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/gjbae1212/kubectl-cred/releases/download/{{ .TagName }}/kubectl-cred_{{ .TagName }}_Windows_x86_64.tar.gz" .TagName }}
    bin: kubectl-cred.exe
