name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  job_build:
    name: goreleaser and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: check gopath
        run: |
          export GOPATH=$(go env GOPATH)
          echo $GOPATH
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
          GOPATH: /home/runner/go
#      - name: Update new version in krew-index
#        uses: rajatjindal/krew-release-bot@v0.0.38
